# Tugas 3 : Data Time Series
Time series merupakan data yang berisi mengenai pengamatan suatu perubahan dalam rentang waktu yang telah ditentukan

In [2]:
import numpy as np
import pandas as pd

## Import data Airline-Passengers

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv')

## Mengambil target data

In [4]:
target = data['Passengers']
print(target)

0      112
1      118
2      132
3      129
4      121
      ...
139    606
140    508
141    461
142    390
143    432
Name: Passengers, Length: 144, dtype: int64

## Split Sequence data
merubah data yang awalnya hanya 1 fitur menjadi beberapa fitur

In [5]:
def split_sequence(sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    # Mencari n akhir
    end_ix = i + n_steps
    # Memeriksa urutan terluar dari data
    if end_ix > len(sequence)-1:
      break
    # Menambahkan bagian input dan output
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return np.array(X), np.array(y)

# Menentukan Waktu dari data time series
jmlh_X = 2
print('Shapes Target = ',target.shape)
#Split data fitur dan target
X, y = split_sequence(target, jmlh_X)
print('Shapes X = ',X.shape)
print('Shapes Y = ',y.shape)

Shapes Target =  (144,)
Shapes X =  (142, 2)
Shapes Y =  (142,)

In [6]:
newFitur = pd.DataFrame(X, columns=['Xt-'+str(i) for i in range(jmlh_X-1, -1,-1)])
newTarget = pd.DataFrame(y, columns=['Data Prediksi'])

In [7]:
newData = pd.concat([newFitur,newTarget], axis=1)
newData

     Xt-1  Xt-0  Data Prediksi
0     112   118            132
1     118   132            129
2     132   129            121
3     129   121            135
4     121   135            148
..    ...   ...            ...
137   535   622            606
138   622   606            508
139   606   508            461
140   508   461            390
141   461   390            432

[142 rows x 3 columns]

## Normalisasi data Fitur
Menggunakan MinMaxScaler

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
X_norm= scaler.fit_transform(newFitur)
# print(X_norm)

In [12]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_norm)
# print(X_pca)

## Split Data training dan Testing
Mengambil data tes sebanyak 20% dari seluruh data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.2, random_state=0)

## Menentukan model
Menggunakan Model KNN dengan jumlah n = 3

In [ ]:
# import knn
from sklearn.neighbors import KNeighborsRegressor
model_knn = KNeighborsRegressor(n_neighbors=3)

In [ ]:
model_knn.fit(X_train, y_train)
y_pred=model_knn.predict(X_test)

## Menghitung MSE (Mean Squared Error)
Rumus MSE :
$$ \text{MSE} = \frac{1}{n} \sum_{i=0}^n (y_i - \hat{y}_i)^2$$

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

In [ ]:
print(y_test.shape,y_pred.shape)

## Hasil

In [ ]:
df_y_test = pd.DataFrame(y_test,columns=['y_test'])
df_y_pred = pd.DataFrame(y_pred,columns=['y_pred'])

df_hasil = pd.concat([df_y_test, df_y_pred], axis=1)
df_hasil.head(29)

### Hasil prediksi Terendah

In [ ]:
y.min()

### Hasil prediksi Tertinggi

In [ ]:
y.max()